name: Scan Features

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/ApplicationInspector-Action@0.9.4
    - uses: actions/upload-artifact@v2
      with:
            name: AppInspectorResults
            path: AppInspectorResults.json
