name: Scan Features

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: AppInspector
      uses: microsoft/ApplicationInspector-Action@v0.9.4
